# Generated by Django 5.2.17 on 2026-09-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('ponto', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
