# Generated by Django 5.2.17 on 2026-09-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Espeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espeto',
            name='ponto',
        ),
    ]
