# Generated by Django 5.2.17 on 2026-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espeto', '0002_remove_espeto_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='espeto',
            name='nome',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
