# Generated by Django 5.2.17 on 2026-09-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Espeto', '0003_espeto_nome'),
        ('Garcom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('garcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garcom.garcom')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('ponto', models.CharField(blank=True, max_length=50, null=True)),
                ('espeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espeto.espeto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.pedido')),
            ],
        ),
    ]
