# Generated by Django 5.2.17 on 2026-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='ponto',
            field=models.CharField(blank=True, choices=[('Mal passado', 'Mal passado'), ('Ao ponto', 'Ao ponto'), ('Bem passado', 'Bem passado')], max_length=50, null=True),
        ),
    ]
