# Generated by Django 5.2.17 on 2026-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_pedido_entregue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregue',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('Em Preparo', 'Em Preparo'), ('Pronto', 'Pronto'), ('Entregue', 'Entregue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='ponto',
            field=models.CharField(blank=True, choices=[('Mal passado', 'Mal passado'), ('Ao ponto', 'Ao ponto'), ('Bem passado', 'Bem passado'), ('Não se aplica', 'Não se aplica')], max_length=50, null=True),
        ),
    ]
