# Generated by Django 5.2.17 on 2026-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0004_remove_itempedido_quantidade_remove_pedido_entregue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('Em espera', 'Em Espera'), ('Em Preparo', 'Em Preparo'), ('Pronto', 'Pronto'), ('Entregue', 'Entregue')], max_length=50, null=True),
        ),
    ]
