# Generated by Django 5.2.17 on 2026-09-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0001_initial'),
        ('Pedido', '0005_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mesa.mesa'),
        ),
    ]
